from __future__ import annotations

from collections.abc import AsyncIterator, Mapping, Sequence
from typing import Protocol

from hekate.domain.models import (
    AgentSpec, CancelObservation, CreateObservation, DeleteObservation,
    DispatchObservation, ExecutionEnvelope, MemoryProjection, MemoryProjectionObservation,
    ProjectionBinding, ProviderAgent,
    ProviderCursor, ProviderObservation, RuntimeBinding, RuntimeCapabilities,
    RuntimeEvent, TurnInput,
)
from hekate.domain.types import DeploymentId, OperationId, ProviderAgentId


class AgentRuntime(Protocol):
    async def capabilities(self) -> RuntimeCapabilities: ...
    async def create_agent(self, spec: AgentSpec, operation_id: OperationId) -> CreateObservation: ...
    async def list_owned_agents(self, owner: DeploymentId, creation_op: OperationId | None) -> Sequence[ProviderAgent]: ...
    async def observe_agent(self, provider_id: ProviderAgentId) -> ProviderObservation: ...
    async def prepare_session(
        self, binding: RuntimeBinding, output_contract: str | None = None, sdk_output_format: bool = True,
    ) -> tuple[RuntimeBinding, Mapping[str, object]]: ...
    async def start_turn(self, binding: RuntimeBinding, capsule: TurnInput, envelope: ExecutionEnvelope) -> DispatchObservation: ...
    async def events(self, cursor: ProviderCursor | None) -> AsyncIterator[RuntimeEvent]: ...
    async def abort(self, binding: RuntimeBinding, operation_id: OperationId) -> CancelObservation: ...
    async def delete_agent(self, provider_id: ProviderAgentId, operation_id: OperationId) -> DeleteObservation: ...
    async def recover_turn(self, binding: RuntimeBinding, otid: str) -> object: ...
    async def read_projected_memory(self, binding: ProjectionBinding, topic_id: object, operation_id: OperationId) -> MemoryProjectionObservation: ...
    async def project_memory(self, projection: MemoryProjection) -> MemoryProjectionObservation: ...
