from __future__ import annotations

from collections.abc import Sequence
from typing import Protocol

from hekate.domain.models import (
    Account, AccountSnapshot, AdmissionReceipt, AdmissionRequest, AgentRecord, AuditEvent,
    Attempt, AuthorizationSnapshot, BillableCallIntent, BudgetReservation,
    CallObservation, CallPermit, EvidenceRecord, ExecutionObservation, InboxReceipt,
    Lease, Operation, OperationClaim, OutboxJob, Page, PositionVersionRecord,
    PublicEvent, Reservation, ReservationRequest, SettlementReceipt, StoredConclusion,
    Task, UsageObservation, UsageReceipt,
)
from hekate.domain.types import (
    AccountingCallId, AttemptId, EvidenceId, OperationId, PermitId, PrincipalId,
    ProviderAgentId, RegistryId, ScopeId, TaskId, TopicId,
)
from collections.abc import Mapping


class TaskRepository(Protocol):
    async def insert_scope(self, snapshot: AuthorizationSnapshot) -> None: ...
    async def lock_scope(self, scope: ScopeId) -> AuthorizationSnapshot: ...
    async def insert_task(self, task: Task, constraints: Mapping[str, object] | None = None) -> None: ...
    async def lock_task(self, task_id: TaskId) -> Task: ...
    async def get_attempt(self, attempt_id: AttemptId, for_update: bool = False) -> Attempt: ...
    async def attempt_exists(self, attempt_id: AttemptId) -> bool: ...
    async def insert_attempt(self, attempt: Attempt) -> None: ...
    async def apply_admission(self, task: Task, attempt_kind: str) -> None: ...
    async def revise_input(self, task_id: TaskId, expected_revision: int, change: object, constraints_hash: str, **kwargs: object) -> Task: ...
    async def request_cancel(self, task_id: TaskId, reason: object) -> Task: ...
    async def confirm_cancelled(self, task_id: TaskId) -> Task: ...
    async def increment_provider_calls(self, task_id: TaskId) -> None: ...
    async def compare_and_set_state(self, task_id: TaskId, expected: object, update: object) -> bool: ...
    async def increment_counter_if_below(self, task_id: TaskId, counter: str, cap: int) -> bool: ...


class AgentRepository(Protocol):
    async def get_persistent_owner(self, owner: PrincipalId) -> AgentRecord | None: ...
    async def insert_intent(self, record: AgentRecord) -> None: ...
    async def bind_provider(self, registry_id: RegistryId, provider_id: ProviderAgentId) -> None: ...
    async def update_observation(self, registry_id: RegistryId, observation: object) -> None: ...
    async def acquire_lease(self, registry_id: RegistryId, owner: str, ttl: float) -> Lease | None: ...
    async def renew_lease(self, lease: Lease) -> Lease: ...
    async def release_lease(self, lease: Lease) -> None: ...
    async def lock_registry(self, registry_id: RegistryId) -> AgentRecord: ...
    async def assert_current_lease(self, registry_id: RegistryId, owner: str, fence: int) -> Lease: ...
    async def get_lease(self, registry_id: RegistryId) -> Lease | None: ...
    async def active_execution_hold(self, registry_id: RegistryId, *, lock: bool = False) -> object: ...
    async def create_execution_hold(self, registry_id: RegistryId, operation_id: OperationId) -> None: ...
    async def set_registry_busy(self, registry_id: RegistryId, attempt_id: str) -> None: ...
    async def set_registry_ready(self, registry_id: RegistryId) -> None: ...


class BudgetRepository(Protocol):
    async def lock_accounts(self, account_ids: Sequence[str]) -> Sequence[Account]: ...
    async def create_account(self, account: AccountSnapshot) -> None: ...
    async def reserve_operation(self, request: ReservationRequest) -> BudgetReservation: ...
    async def get_reservation(self, reservation_id: ReservationId, *, lock: bool = False) -> Mapping[str, object] | None: ...
    async def allocate_call(self, intent: BillableCallIntent, reservation_id: object, attempt_id: AttemptId, envelope: object, intent_hash: str) -> CallPermit: ...
    async def get_call_descriptor(self, accounting_call_id: AccountingCallId) -> Mapping[str, object] | None: ...
    async def get_call(self, accounting_call_id: AccountingCallId, *, lock: bool = False) -> Mapping[str, object] | None: ...
    async def count_calls_by_kind(self, operation_id: OperationId, call_kind: str) -> int: ...
    async def lock_call_accounts(self, accounting_call_id: AccountingCallId) -> Sequence[Account]: ...
    async def consume_call_permit(self, permit_id: PermitId, accounting_call_id: AccountingCallId) -> CallPermit: ...
    async def record_call_observation(self, observation: CallObservation) -> None: ...
    async def record_usage(self, observation: UsageObservation) -> UsageReceipt: ...
    async def settle_call(self, accounting_call_id: AccountingCallId) -> SettlementReceipt: ...
    async def call_ids_for_operation(self, operation_id: OperationId) -> Sequence[str]: ...
    async def call_ids_for_reservation(self, reservation_id: ReservationId) -> Sequence[str]: ...
    async def release_unallocated_after_quiescence(self, operation_id: OperationId) -> None: ...
    async def apply_adjustment(self, account_id: str, effect_key: str, amount: object, **kwargs: object) -> bool: ...
    async def list_pending_calls(self, limit: int = 100) -> Sequence[Mapping[str, object]]: ...


class KnowledgeRepository(Protocol):
    async def lock_topic(self, scope: ScopeId, topic_id: TopicId) -> object: ...
    async def append_position(self, record: PositionVersionRecord) -> None: ...
    async def cas_current(self, topic_id: TopicId, base: int, new: int) -> bool: ...
    async def insert_evidence(self, record: EvidenceRecord) -> None: ...
    async def get_evidence(self, ids: Sequence[EvidenceId], lock: bool = False) -> Sequence[EvidenceRecord]: ...
    async def lock_accessible_references(self, refs: Sequence[EvidenceId]) -> object: ...
    async def insert_conclusion(self, record: StoredConclusion) -> None: ...
    async def get_eligible_conclusions(self, task_id: TaskId, revision: int) -> Sequence[StoredConclusion]: ...
    async def set_projection_watermark(self, target: object, version: int) -> None: ...


class DeliveryRepository(Protocol):
    async def claim_operation(self, operation_id: OperationId, owner_scope: ScopeId, task_id: TaskId, kind: str, request_hash: str, binding: Mapping[str, object], envelope: Mapping[str, object]) -> OperationClaim: ...
    async def lock_operation(self, operation_id: OperationId, request_hash: str | None = None) -> Mapping[str, object]: ...
    async def lock_task_operations(self, task_id: TaskId) -> Sequence[Mapping[str, object]]: ...
    async def complete_admission(self, receipt: AdmissionReceipt) -> None: ...
    async def store_commit_receipt(self, operation_id: OperationId, request_hash: str, receipt: object) -> None: ...
    async def update_operation(self, operation_id: OperationId, expected: object, observation: object) -> None: ...
    async def append_outbox(self, job: OutboxJob) -> None: ...
    async def claim_jobs(self, worker: str, limit: int, lease: float) -> Sequence[OutboxJob]: ...
    async def get_dispatch_payload(self, operation_id: OperationId) -> Mapping[str, object] | None: ...
    async def record_send_intent(self, job: OutboxJob, worker: str, fence: int) -> None: ...
    async def mark_dispatch_accepted(self, job: OutboxJob, worker: str, fence: int) -> None: ...
    async def ack_job(self, job: OutboxJob, worker: str, fence: int) -> None: ...
    async def reschedule_job(self, job: OutboxJob, worker: str, fence: int, error: str, delay: float) -> None: ...
    async def insert_inbox_once(self, provider_scope: str, stable_event_key: str, payload: Mapping[str, object], payload_hash: str) -> InboxReceipt: ...
    async def lock_inbox(self, inbox_id: str) -> Mapping[str, object] | None: ...
    async def mark_inbox_processed(self, inbox_id: str) -> None: ...
    async def pending_inbox(self, limit: int = 100) -> Sequence[Mapping[str, object]]: ...
    async def record_execution(self, observation: ExecutionObservation) -> None: ...
    async def append_audit(self, event: AuditEvent) -> None: ...
    async def read_public_events(self, task_id: TaskId, after: object) -> Page[PublicEvent]: ...


class UnitOfWork(Protocol):
    tasks: TaskRepository
    agents: AgentRepository
    budgets: BudgetRepository
    knowledge: KnowledgeRepository
    delivery: DeliveryRepository

    async def __aenter__(self) -> UnitOfWork: ...
    async def __aexit__(self, exc_type: object, exc: object, traceback: object) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...


class UowFactory(Protocol):
    def __call__(self) -> UnitOfWork: ...
