from __future__ import annotations

from collections.abc import Sequence
from typing import Protocol

from hekate.domain.models import (
    Account, AgentRecord, AuditEvent, Attempt, AuthorizationSnapshot,
    BudgetReservation, EvidenceRecord, Job, Lease, Operation, OperationClaim,
    Page, PositionVersionRecord, PublicEvent, Reservation, StoredConclusion,
    Task, UsageRecord,
)
from hekate.domain.types import (
    AttemptId, EvidenceId, OperationId, PrincipalId, ProviderAgentId,
    RegistryId, ScopeId, TaskId, TopicId,
)


class TaskRepository(Protocol):
    async def lock_scope(self, scope: ScopeId) -> AuthorizationSnapshot: ...
    async def insert_task(self, task: Task) -> None: ...
    async def lock_task(self, task_id: TaskId) -> Task: ...
    async def get_attempt(self, attempt_id: AttemptId, for_update: bool = False) -> Attempt: ...
    async def insert_attempt(self, attempt: Attempt) -> None: ...
    async def compare_and_set_state(self, task_id: TaskId, expected: object, update: object) -> bool: ...
    async def increment_counter_if_below(self, task_id: TaskId, counter: str, cap: int) -> bool: ...


class AgentRepository(Protocol):
    async def get_persistent_owner(self, owner: PrincipalId) -> AgentRecord | None: ...
    async def insert_intent(self, record: AgentRecord) -> None: ...
    async def bind_provider(self, registry_id: RegistryId, provider_id: ProviderAgentId) -> None: ...
    async def update_observation(self, registry_id: RegistryId, observation: object) -> None: ...
    async def acquire_lease(self, registry_id: RegistryId, owner: str, ttl: float) -> Lease | None: ...
    async def renew_lease(self, lease: Lease) -> Lease: ...
    async def release_lease(self, lease: Lease) -> None: ...


class BudgetRepository(Protocol):
    async def lock_accounts(self, account_ids: Sequence[str]) -> Sequence[Account]: ...
    async def insert_reservation(self, reservation: BudgetReservation) -> None: ...
    async def allocate_call(self, permit: object) -> None: ...
    async def upsert_usage(self, usage: UsageRecord) -> bool: ...
    async def apply_settlement(self, settlement: object) -> None: ...
    async def list_pending(self, cursor: object) -> Page[Reservation]: ...


class KnowledgeRepository(Protocol):
    async def lock_topic(self, scope: ScopeId, topic_id: TopicId) -> object: ...
    async def append_position(self, record: PositionVersionRecord) -> None: ...
    async def cas_current(self, topic_id: TopicId, base: int, new: int) -> bool: ...
    async def insert_evidence(self, record: EvidenceRecord) -> None: ...
    async def get_evidence(self, ids: Sequence[EvidenceId], lock: bool = False) -> Sequence[EvidenceRecord]: ...
    async def lock_accessible_references(self, refs: Sequence[EvidenceId]) -> object: ...
    async def insert_conclusion(self, record: StoredConclusion) -> None: ...
    async def get_eligible_conclusions(self, task_id: TaskId, revision: int) -> Sequence[StoredConclusion]: ...
    async def set_projection_watermark(self, target: object, version: int) -> None: ...


class DeliveryRepository(Protocol):
    async def claim_operation(self, operation_id: OperationId, request_hash: str) -> OperationClaim: ...
    async def lock_operation(self, operation_id: OperationId, request_hash: str) -> Operation: ...
    async def store_commit_receipt(self, operation_id: OperationId, request_hash: str, receipt: object) -> None: ...
    async def update_operation(self, operation_id: OperationId, expected: object, observation: object) -> None: ...
    async def append_outbox(self, job: Job) -> None: ...
    async def claim_jobs(self, worker: str, limit: int, lease: float) -> Sequence[Job]: ...
    async def ack_job(self, job: Job, fence: int) -> None: ...
    async def reschedule_job(self, job: Job, error: str, delay: float) -> None: ...
    async def insert_inbox_once(self, event: object) -> object: ...
    async def append_audit(self, event: AuditEvent) -> None: ...
    async def read_public_events(self, task_id: TaskId, after: object) -> Page[PublicEvent]: ...


class UnitOfWork(Protocol):
    tasks: TaskRepository
    agents: AgentRepository
    budgets: BudgetRepository
    knowledge: KnowledgeRepository
    delivery: DeliveryRepository

    async def __aenter__(self) -> UnitOfWork: ...
    async def __aexit__(self, exc_type: object, exc: object, traceback: object) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...


class UowFactory(Protocol):
    def __call__(self) -> UnitOfWork: ...
