from __future__ import annotations

from collections.abc import Sequence
from datetime import datetime
from typing import Protocol

from hekate.domain.models import (
    Account, AccountSnapshot, AdmissionReceipt, AdmissionRequest, AgentRecord, AuditEvent, CriticWorkflow,
    Attempt, AuthorizationSnapshot, AuthorizationScopeState, BillableCallIntent, BudgetReservation,
    CallObservation, CallPermit, DissentExcerpt, EvidenceRecord,
    ExecutionObservation, HistoryPage, InboxReceipt, Lease, Operation, OperationClaim,
    OutboxJob, Page, PositionTopicView, PositionVersionRecord, PositionView,
    ProjectionJob, ProjectionReadBackSnapshot, MemoryProjection, PublicEvent, Reservation, ReservationRequest, SettlementReceipt, StoredConclusion,
    Task, UsageObservation, UsageReceipt,
)
from hekate.domain.types import (
    AccountingCallId, AttemptId, EvidenceId, OperationId, PermitId, PrincipalId,
    ProviderAgentId, RegistryId, ScopeId, TaskId, TopicId,
)
from collections.abc import Mapping


class TaskRepository(Protocol):
    async def insert_scope(self, snapshot: AuthorizationSnapshot) -> None: ...
    async def lock_scope(self, scope: ScopeId) -> AuthorizationSnapshot: ...
    async def lock_scope_for_observation(self, scope: ScopeId) -> AuthorizationScopeState: ...
    async def claim_submission(self, scope: ScopeId, request_key: str, request_hash: str) -> Mapping[str, object]: ...
    async def complete_submission(self, scope: ScopeId, request_key: str, task_id: TaskId, receipt: Mapping[str, object]) -> None: ...
    async def get_submission_request_key(self, scope: ScopeId, task_id: TaskId) -> str | None: ...
    async def insert_task(self, task: Task, constraints: Mapping[str, object] | None = None) -> None: ...
    async def lock_task(self, task_id: TaskId) -> Task: ...
    async def get_task_input(self, task_id: TaskId, revision: int) -> Mapping[str, object] | None: ...
    async def get_attempt(self, attempt_id: AttemptId, for_update: bool = False) -> Attempt: ...
    async def attempt_exists(self, attempt_id: AttemptId) -> bool: ...
    async def insert_attempt(self, attempt: Attempt) -> None: ...
    async def apply_admission(self, task: Task, attempt_kind: str) -> None: ...
    async def revise_input(self, task_id: TaskId, expected_revision: int, change: object, constraints_hash: str, **kwargs: object) -> Task: ...
    async def request_cancel(self, task_id: TaskId, reason: object) -> Task: ...
    async def increment_provider_calls(self, task_id: TaskId) -> None: ...
    async def compare_and_set_state(self, task_id: TaskId, expected: object, update: object) -> bool: ...
    async def increment_counter_if_below(self, task_id: TaskId, counter: str, cap: int) -> bool: ...
    async def list_queued(self, limit: int = 20) -> Sequence[Mapping[str, object]]: ...
    async def claim_task_preparation(self, task_id: TaskId, revision: int, operation_id: str, attempt_id: str, reservation_id: str, owner: str, ttl_seconds: int) -> Mapping[str, object]: ...
    async def mark_task_preparation_admitted(self, task_id: TaskId, revision: int, owner: str, conversation_id: str, fence: int) -> None: ...
    async def release_task_preparation(self, task_id: TaskId, revision: int, owner: str) -> None: ...
    async def fail_expired_queued(self, now: object) -> int: ...
    async def fail_queued_task(self, task_id: TaskId, reason: object) -> bool: ...
    async def get_task_response(self, task_id: TaskId) -> Mapping[str, object] | None: ...
    async def fail_waiting_task_with_response(self, task_id: TaskId, revision: int, response: Mapping[str, object]) -> bool: ...
    async def resolve_waiting_task_with_response(
        self, task_id: TaskId, revision: int, response: Mapping[str, object], *, successful: bool,
    ) -> bool: ...
    async def get_task_cost_status(self, task_id: TaskId) -> Mapping[str, object]: ...
    async def finalize_task_response(self, task_id: TaskId, revision: int, response: Mapping[str, object], *, successful: bool, accepted_at: datetime | None = None) -> bool: ...
    async def fail_unaccepted_execution_with_policy_response(
        self, scope: ScopeId, expected_authorization: AuthorizationSnapshot, task_id: TaskId,
        revision: int, response: Mapping[str, object], *, accepted_at: datetime,
    ) -> bool: ...
    async def resolve_task_after_execution(self, task_id: TaskId, revision: int, *, now: datetime | None = None) -> Task | None: ...
    async def list_execution_terminal_candidates(self, limit: int = 100) -> Sequence[Mapping[str, object]]: ...
    async def list_pending_turn_results(self, limit: int = 100, owner_scope: ScopeId | None = None) -> Sequence[str]: ...
    async def set_base_position_version(self, task_id: TaskId, revision: int, version: int) -> bool: ...
    async def fail_policy_task(self, task_id: TaskId, revision: int) -> bool: ...
    async def mark_waiting_for_workflow(self, task_id: TaskId, revision: int) -> bool: ...


class AgentRepository(Protocol):
    async def get_persistent_owner(self, owner: PrincipalId) -> AgentRecord | None: ...
    async def get_persistent_scope(self, owner_scope: ScopeId, *, lock: bool = False) -> AgentRecord | None: ...
    async def insert_intent(self, record: AgentRecord) -> None: ...
    async def bind_provider(self, registry_id: RegistryId, provider_id: ProviderAgentId) -> None: ...
    async def update_observation(self, registry_id: RegistryId, observation: object) -> None: ...
    async def acquire_lease(self, registry_id: RegistryId, owner: str, ttl: float) -> Lease | None: ...
    async def renew_lease(self, lease: Lease) -> Lease: ...
    async def release_lease(self, lease: Lease) -> None: ...
    async def lock_registry(self, registry_id: RegistryId) -> AgentRecord: ...
    async def get_registry(self, registry_id: RegistryId, *, lock: bool = False) -> AgentRecord | None: ...
    async def assert_current_lease(self, registry_id: RegistryId, owner: str, fence: int) -> Lease: ...
    async def get_lease(self, registry_id: RegistryId, *, lock: bool = False) -> Lease | None: ...
    async def active_execution_hold(self, registry_id: RegistryId, *, lock: bool = False) -> object: ...
    async def create_execution_hold(self, registry_id: RegistryId, operation_id: OperationId) -> None: ...
    async def set_registry_busy(self, registry_id: RegistryId, attempt_id: str) -> None: ...
    async def set_registry_ready(self, registry_id: RegistryId) -> None: ...
    async def set_registry_deleting(self, registry_id: RegistryId) -> None: ...
    async def mark_registry_deleted(self, registry_id: RegistryId) -> None: ...


class BudgetRepository(Protocol):
    async def lock_accounts(self, account_ids: Sequence[str]) -> Sequence[Account]: ...
    async def create_account(self, account: AccountSnapshot) -> None: ...
    async def ensure_account(self, account: AccountSnapshot) -> None: ...
    async def reserve_operation(self, request: ReservationRequest) -> BudgetReservation: ...
    async def get_reservation(self, reservation_id: ReservationId, *, lock: bool = False) -> Mapping[str, object] | None: ...
    async def allocate_call(self, intent: BillableCallIntent, reservation_id: object, attempt_id: AttemptId, envelope: object, intent_hash: str) -> CallPermit: ...
    async def get_call_descriptor(self, accounting_call_id: AccountingCallId) -> Mapping[str, object] | None: ...
    async def get_call(self, accounting_call_id: AccountingCallId, *, lock: bool = False) -> Mapping[str, object] | None: ...
    async def count_calls_by_kind(self, operation_id: OperationId, call_kind: str) -> int: ...
    async def lock_call_accounts(self, accounting_call_id: AccountingCallId) -> Sequence[Account]: ...
    async def consume_call_permit(self, permit_id: PermitId, accounting_call_id: AccountingCallId) -> CallPermit: ...
    async def record_call_observation(self, observation: CallObservation) -> None: ...
    async def record_usage(self, observation: UsageObservation) -> UsageReceipt: ...
    async def settle_call(self, accounting_call_id: AccountingCallId) -> SettlementReceipt: ...
    async def call_ids_for_operation(self, operation_id: OperationId) -> Sequence[str]: ...
    async def call_ids_for_reservation(self, reservation_id: ReservationId) -> Sequence[str]: ...
    async def release_unallocated_after_quiescence(self, operation_id: OperationId) -> None: ...
    async def apply_adjustment(self, account_id: str, effect_key: str, amount: object, **kwargs: object) -> bool: ...
    async def list_pending_calls(self, limit: int = 100, owner_scope: ScopeId | None = None) -> Sequence[Mapping[str, object]]: ...


class KnowledgeRepository(Protocol):
    async def lock_topic(self, scope: ScopeId, topic_id: TopicId) -> int: ...
    async def append_position(self, record: PositionVersionRecord) -> None: ...
    async def cas_current(self, scope: ScopeId, topic_id: TopicId, base: int, new: int) -> bool: ...
    async def insert_evidence(self, record: EvidenceRecord) -> None: ...
    async def get_evidence(self, ids: Sequence[EvidenceId], lock: bool = False) -> Sequence[EvidenceRecord]: ...
    async def lock_accessible_references(self, scope: ScopeId, refs: Sequence[EvidenceId], access_epoch: int, **kwargs: object) -> Sequence[EvidenceRecord]: ...
    async def stage_artifact(self, ref: str, digest: str, size: int, retention_class: str) -> None: ...
    async def mark_artifact_available(self, ref: str) -> None: ...
    async def get_artifact(self, ref: str) -> Mapping[str, object] | None: ...
    async def register_evidence_import(self, scope: ScopeId, request_key: str, request_hash: str, evidence_id: EvidenceId) -> Mapping[str, object]: ...
    async def get_evidence_import(self, scope: ScopeId, request_key: str) -> Mapping[str, object] | None: ...
    async def expire_evidence(self, now: object, limit: int) -> Sequence[str]: ...
    async def pending_archive_deletions(self, limit: int = 100) -> Sequence[Mapping[str, object]]: ...
    async def archive_delete_is_pending(self, ref: str) -> bool: ...
    async def finish_archive_delete(self, ref: str, *, deleted: bool) -> None: ...
    async def get_current_position(self, scope: ScopeId, topic_id: TopicId, registry_id: RegistryId | None = None) -> PositionTopicView: ...
    async def get_position_history(self, scope: ScopeId, topic_id: TopicId, after_version: int, limit: int, registry_id: RegistryId | None = None) -> Sequence[PositionView]: ...
    async def save_context_manifest(self, operation_id: OperationId, task_id: TaskId, revision: int, manifest: Mapping[str, object]) -> None: ...
    async def get_context_manifest(self, operation_id: OperationId) -> Mapping[str, object] | None: ...
    async def ensure_dissent(self, scope: ScopeId, conclusion_id: object, objections: Sequence[object]) -> Sequence[object]: ...
    async def get_dissent_context(self, scope: ScopeId, refs: Sequence[object]) -> Sequence[DissentExcerpt]: ...
    async def get_dissent_for_conclusion(self, scope: ScopeId, conclusion_id: object) -> Sequence[object]: ...
    async def valid_dissent_refs(self, scope: ScopeId, refs: Sequence[object]) -> bool: ...
    async def upsert_projection(self, scope: ScopeId, topic_id: TopicId, registry_id: RegistryId, version: int) -> None: ...
    async def get_commit_receipt(self, operation_id: OperationId) -> Mapping[str, object] | None: ...
    async def insert_commit_receipt(self, operation_id: OperationId, request_hash: str, scope: ScopeId, registry_id: RegistryId, receipt: Mapping[str, object]) -> None: ...
    async def insert_conclusion(self, record: StoredConclusion) -> None: ...
    async def save_turn_result(self, values: Mapping[str, object]) -> None: ...
    async def lock_turn_result(self, inbox_id: str) -> Mapping[str, object] | None: ...
    async def update_turn_result(self, inbox_id: str, *, state: str, proposal: object = None, conclusion_id: str | None = None, rejection_reason: str | None = None, delay_seconds: float = 0) -> None: ...
    async def get_conclusion(self, conclusion_id: str) -> Mapping[str, object] | None: ...
    async def accepted_turn_result_for_conclusion(self, conclusion_id: str) -> Mapping[str, object] | None: ...
    async def set_conclusion_eligible(self, conclusion_id: str, eligible: bool, reason: str | None) -> None: ...
    async def get_eligible_conclusions(self, task_id: TaskId, revision: int) -> Sequence[StoredConclusion]: ...
class ProjectionRepository(Protocol):
    async def enable_pending(self, limit: int = 100) -> int: ...
    async def claim_due(self, worker: str, scope: ScopeId, limit: int, lease_seconds: int = 120) -> Sequence[ProjectionJob]: ...
    async def start_operation(self, job: ProjectionJob, operation_id: object, request_hash: str, payload_digest: str, source_version: int, base_applied_version: int) -> Mapping[str, object]: ...
    async def capture_read_back_snapshot(self, job: ProjectionJob, projection: MemoryProjection) -> ProjectionReadBackSnapshot: ...
    async def resolve_write_guards_after_read(self, job: ProjectionJob, snapshot: ProjectionReadBackSnapshot, observation: object) -> int: ...
    async def claim_generation_allows_lease_release(self, job: ProjectionJob, operation_id: OperationId) -> bool: ...
    async def finish(self, job: ProjectionJob, operation_id: object, observation: Mapping[str, object], **kwargs: object) -> bool: ...
    async def fail(self, job: ProjectionJob, operation_id: object | None, reason: str, **kwargs: object) -> None: ...
    async def release_stale_claim(self, job: ProjectionJob, *, reason: str, delay_seconds: int = 5) -> None: ...
    async def get_status(self, scope: object, topic_id: object, registry_id: object) -> Mapping[str, object] | None: ...


class DeliveryRepository(Protocol):
    async def claim_lifecycle_operation(self, operation_id: OperationId, owner_scope: ScopeId, kind: str, request_hash: str) -> Mapping[str, object]: ...
    async def mark_lifecycle_started(self, operation_id: OperationId, kind: str) -> bool: ...
    async def complete_lifecycle_operation(self, operation_id: OperationId, observation: Mapping[str, object]) -> None: ...
    async def mark_lifecycle_unknown(self, operation_id: OperationId, reason: str) -> None: ...
    async def claim_operation(self, operation_id: OperationId, owner_scope: ScopeId, task_id: TaskId, kind: str, request_hash: str, binding: Mapping[str, object], envelope: Mapping[str, object], workflow_stage_hash: str | None = None) -> OperationClaim: ...
    async def claim_deferred_operation(self, operation_id: OperationId, owner_scope: ScopeId, task_id: TaskId, kind: str, stage_hash: str) -> None: ...
    async def reject_deferred_operation(self, operation_id: OperationId, task_id: TaskId, stage_hash: str, reason: str) -> bool: ...
    async def lock_operation(self, operation_id: OperationId, request_hash: str | None = None) -> Mapping[str, object]: ...
    async def get_operation_statuses(self, operation_ids: Sequence[OperationId]) -> Mapping[str, Mapping[str, object]]: ...
    async def lock_task_operations(self, task_id: TaskId) -> Sequence[Mapping[str, object]]: ...
    async def task_execution_states(self, task_id: TaskId) -> Sequence[Mapping[str, object]]: ...
    async def complete_admission(self, receipt: AdmissionReceipt) -> None: ...
    async def store_commit_receipt(self, operation_id: OperationId, request_hash: str, receipt: object) -> None: ...
    async def update_operation(self, operation_id: OperationId, expected: object, observation: object) -> None: ...
    async def append_outbox(self, job: OutboxJob) -> None: ...
    async def claim_jobs(self, worker: str, limit: int, lease: float) -> Sequence[OutboxJob]: ...
    async def claim_lifecycle_jobs(self, worker: str, limit: int, lease: float) -> Sequence[OutboxJob]: ...
    async def get_dispatch_payload(self, operation_id: OperationId) -> Mapping[str, object] | None: ...
    async def record_send_intent(self, job: OutboxJob, worker: str, fence: int) -> None: ...
    async def mark_dispatch_accepted(self, job: OutboxJob, worker: str, fence: int) -> None: ...
    async def ack_job(self, job: OutboxJob, worker: str, fence: int) -> None: ...
    async def assert_job_claim(self, job: OutboxJob, worker: str, fence: int) -> None: ...
    async def reschedule_job(self, job: OutboxJob, worker: str, fence: int, error: str, delay: float) -> None: ...
    async def insert_inbox_once(self, provider_scope: str, stable_event_key: str, payload: Mapping[str, object], payload_hash: str) -> InboxReceipt: ...
    async def processed_inbox_id(self, provider_scope: str, stable_event_key: str, payload_hash: str) -> str | None: ...
    async def lock_inbox(self, inbox_id: str) -> Mapping[str, object] | None: ...
    async def mark_inbox_processed(self, inbox_id: str) -> None: ...
    async def defer_inbox(self, inbox_id: str, reason: str, delay: float = 1.0) -> None: ...
    async def reject_inbox(self, inbox_id: str, reason: str) -> None: ...
    async def pending_inbox(self, limit: int = 100, owner_scope: ScopeId | None = None) -> Sequence[Mapping[str, object]]: ...
    async def pending_terminal_inbox(self, operation_id: OperationId) -> Sequence[Mapping[str, object]]: ...
    async def record_execution(self, observation: ExecutionObservation) -> None: ...
    async def append_audit(self, event: AuditEvent) -> None: ...
    async def read_public_events(self, task_id: TaskId, after: object) -> Page[PublicEvent]: ...


class CriticWorkflowRepository(Protocol):
    async def insert(self, workflow: CriticWorkflow) -> None: ...
    async def get(self, task_id: TaskId, *, lock: bool = False) -> CriticWorkflow | None: ...
    async def get_by_create_operation(self, operation_id: OperationId, *, lock: bool = False) -> CriticWorkflow | None: ...
    async def list_stages(self, stages: Sequence[str], limit: int = 100) -> Sequence[CriticWorkflow]: ...
    async def transition(self, task_id: TaskId, expected: Sequence[str], stage: str, **values: object) -> CriticWorkflow: ...
    async def authorize_admission(self, *, task_id: TaskId, scope: ScopeId, stage: str, attempt_id: AttemptId, operation_id: OperationId, registry_id: RegistryId) -> CriticWorkflow: ...


class DeliberationRepository(Protocol):
    async def insert(self, value: Mapping[str, object]) -> None: ...
    async def get(self, step_id: str, *, lock: bool = False) -> Mapping[str, object] | None: ...
    async def get_by_operation(self, operation_id: str, *, lock: bool = False) -> Mapping[str, object] | None: ...
    async def get_by_parent_proposal(self, task_id: TaskId, parent_operation_id: str, proposal_hash: str, *, lock: bool = False) -> Mapping[str, object] | None: ...
    async def get_by_work_fingerprint(self, task_id: TaskId, fingerprint: str) -> Mapping[str, object] | None: ...
    async def list_ready(self, scope: ScopeId, limit: int = 20) -> Sequence[Mapping[str, object]]: ...
    async def list_maintenance_candidates(self, limit: int = 100) -> Sequence[Mapping[str, object]]: ...
    async def mark_maintenance_complete(self, step: Mapping[str, object]) -> bool: ...
    async def defer_maintenance_retry(self, step: Mapping[str, object], retry_after: datetime) -> bool: ...
    async def list_for_task(self, task_id: TaskId, *, lock: bool = False) -> Sequence[Mapping[str, object]]: ...
    async def transition(self, step_id: str, expected: Sequence[str], state: str, *, conclusion_id: str | None = None, parent_conclusion_id: str | None = None, stop_reason: str | None = None) -> None: ...
    async def set_ready(self, step_id: str, expected: Sequence[str]) -> None: ...
    async def mark_admitted(self, step_id: str) -> None: ...
    async def mark_result_accepted(self, step_id: str, conclusion_id: str) -> None: ...
    async def mark_complete(self, step_id: str) -> None: ...
    @staticmethod
    def stage_hash(row: Mapping[str, object]) -> str: ...


class UnitOfWork(Protocol):
    tasks: TaskRepository
    agents: AgentRepository
    budgets: BudgetRepository
    knowledge: KnowledgeRepository
    delivery: DeliveryRepository
    critic_workflows: CriticWorkflowRepository
    deliberation: DeliberationRepository
    projections: ProjectionRepository

    async def __aenter__(self) -> UnitOfWork: ...
    async def __aexit__(self, exc_type: object, exc: object, traceback: object) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...


class UowFactory(Protocol):
    def __call__(self) -> UnitOfWork: ...
